export * from './img/vaca1_480.png';
export * from './img/google.png';
export * from './img/G.png';
export * from './img/vaca2.png';
export * from './img/imgAlienDashboard.png';
export * from './img/ovni.gif';
export * from './img/404logo.png';
export * from './img/imgLuna.png';
export * from './img/github.png';
